import 'package:flutter/material.dart';
import 'package:top_in_city/presentation/core/model/menu_model.dart';

///list of Colors for gradient of text.
const gradientColors = [
  Color(0xffA6A021),
  Color(0xffFF0303),
];
const List<String> footerLinks = [
  'HOME',
  'SERVICES',
  'CATERING MENU',
  'CONTACT',
  'BOOKING',
];
const String sadhyaPackages = 'Sadhya Packages ( Veg )';
const String nonVegFoodMenu = 'Non-Veg Food Menu';
const String sweetsDessertsJuices = 'Sweets / Desserts / Juices';
final Map<String, List<MenuModel>> menuMap = {
  sadhyaPackages: [
    MenuModel(
      price: 80,
      malayalamItems: [
        'റൈസ്',
        'സാമ്പാർ',
        'കൂട്ടുകറി',
        'അച്ചാർ',
        'ഉപ്പേരി',
        'രസം',
        'മോര്',
        'സേമിയപായസം',
        'പപ്പടം',
        'വെള്ളം',
        'ഇല',
        'ഗ്ലാസ്സ്',
        'ടേബിൾ പേപ്പർ',
      ],
      englishItems: [
        'RICE',
        'SAMBAR',
        'KOOTTU CURRY',
        'PICKLE',
        'UPPERI',
        'RASAM',
        'MORU',
        'SEMIYA PAYASAM',
        'PAPPADAM',
        'WATER',
        'LEAF',
        'GLASS',
        'TABLE PAPER',
      ],
    ),
    MenuModel(
      price: 110,
      malayalamItems: [
        'റൈസ്',
        'സാമ്പാർ',
        'കൂട്ടുകറി',
        'അവിയൽ',
        'ഇഞ്ചിപ്പുളി',
        'ഇഷ്ടു',
        'തോരൻ',
        'നാരങ്ങാ അച്ചാർ',
        'രസം',
        'മോര്',
        'സേമിയ പായസം',
        'പപ്പടം',
        'ചുക്കുവെള്ളം',
        'കൊണ്ടാട്ടം',
        'ഇല',
        'ഗ്ലാസ്സ്',
        'ടേബിൾ പേപ്പർ',
      ],
      englishItems: [
        'RICE',
        'SAMBAR',
        'KOOTTU CURRY',
        'AVIYAL',
        'INJIPULI',
        'ISHTU',
        'THORAN',
        'LEMON PICKLE',
        'RASAM',
        'MORU',
        'SEMIYA PAYASAM',
        'PAPPADAM',
        'CHUKKU WATER',
        'KONDATAM',
        'LEAF',
        'GLASS',
        'TABLE PAPER'
      ],
    ),
    MenuModel(
      price: 130,
      malayalamItems: [
        'റൈസ് (പൊന്നി)',
        'സാമ്പാർ',
        'കൂട്ടുകറി',
        'അവിയൽ ',
        'ഇഞ്ചിപ്പുളി ',
        'ഇഷ്ടു',
        'പൈനാപ്പിൽ പച്ചടി',
        'കുറുക്കു  കാളൻ',
        'തോരൻ',
        'നാരങ്ങാ അച്ചാർ',
        'രസം',
        'മോര്',
        'പപ്പടം - 2',
        'ശർക്കര ഉപ്പേരി',
        'കായ വറുത്തത്',
        'നെയ്യപ്പരിപ്പ്',
        'വെളുത്തുള്ളി ചമ്മന്തി',
        'പാലട പായസം',
        'ചുക്ക് വെള്ളം',
        'ഇല',
        'ഡിസ്പോസബിൾ ഗ്ലാസ്സ്',
        'ടേബിൾ പേപ്പർ',
      ],
      englishItems: [
        'RICE (PONNI)',
        'SAMBAR',
        'KOOTTU CURRY',
        'AVIYAL',
        'INJIPULI',
        'ISHTU',
        'PINEAPPLE PACHADI',
        'KURUKKU KALAN',
        'THORAN',
        'LEMON PICKLE',
        'RASAM',
        'MORU',
        'PAPPADAM - 2',
        'SARKARA UPPERI',
        'KAYA VARUTHATHU',
        'GHEE DHAL',
        'VELUTHULLI CHAMMANDI',
        'PALADA PAYASAM',
        'CHUKKU VELLAM',
        'LEAF',
        'DISPOSABLE GLASS',
        'TABLE PAPER',
      ],
    ),
    MenuModel(
      price: 160,
      malayalamItems: [
        'റൈസ് (പൊന്നി)',
        'സാമ്പാർ',
        'പൈനാപ്പിൽ പച്ചടി',
        'കുറുക്കു  കാളൻ',
        'കൂട്ടുകറി',
        'ഇഞ്ചി കറി',
        'ഇഷ്ടു',
        'അവിയൽ',
        'ഇഞ്ചിപ്പുളി',
        'തോരൻ',
        'മസാല കറി',
        'നാരങ്ങാ അച്ചാർ',
        'കൊണ്ടാട്ടം',
        'രസം',
        'മോര്',
        'പപ്പടം - 2',
        'ശർക്കര ഉപ്പേരി',
        'കായ വറുത്തത്',
        'നെയ്യപ്പരിപ്പ്',
        'പാലട പായസം',
        'രണ്ടാം പായസം',
        'ചുക്ക് വെള്ളം',
        'ഇല',
        'ഡിസ്പോസബിൾ ഗ്ലാസ്സ്',
        'ടേബിൾ പേപ്പർ',
      ],
      englishItems: [
        'RICE (PONNI)',
        'SAMBAR',
        'PINEAPPLE PACHADI',
        'KURUKKU KALAN',
        'KOOTTU CURRY',
        'GINGER CURRY',
        'ISHTU',
        'AVIYAL',
        'INJIPULI',
        'THORAN',
        'MASALA CURRY',
        'LEMON PICKLE',
        'KONDATTAM',
        'RASAM',
        'MORU',
        'PAPPADAM - 2',
        'SARKARA UPPERI',
        'KAYA VARUTHATHU',
        'GHEE DHAL',
        'PALADA PAYASAM',
        'SECOND PAYASAM',
        'CHUKKU WATER',
        'LEAF',
        'DISPOSABLE GLASS',
        'TABLE PAPER',
      ],
    ),
  ],
  nonVegFoodMenu: [
    MenuModel(
      englishName: 'CHICKEN',
      malayalamName: 'Chicken',
      malayalamItems: [
        'Chicken Chilly',
        'Chicken Chilly',
        'Chicken Chilly',
      ],
      englishItems: [
        'Chicken Chilly',
        'Chicken Chilly',
        'Chicken Chilly',
      ],
    ),
  ],
  sweetsDessertsJuices: [],
};
